language: ruby
rvm:
- 2.7.2
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle install --jobs=3 --retry=3
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: FCTrnCLOZ5MKBcZ86SdZIHS2MYW5U4t+OZHQmNM5QGREdH9Gns56xH4nbhenRKdpB48gLuBLp6XzvefxnlEdL/q5cSGTuI7K92DjyAaA/Hq+tN8I0v301PX1hQzSngppgIDmMfS8Cm4GNuUTMWA4PxWmAxjlWjDHb2oLAPuUo8dWwPGqp+jwvAhd+m7LVfLxYzcwlUVTvggPDQcCjqdxXQo0yTQG/pTJKmgaZSsg3LE9hXYSnUzZihhTc/M8hqSZkzphJT97nMWS+Xk/YDh+MJko64RmI9ThJLuNT4WtfAz+Kv9DxqwQao7T/vdFCITzsXZwdsL+jXLMDbM8w7S66CuK7KvjoZxQBDYeNGBRFBOPFfYtKCRI+gVmR46ubASDQVEmyqr3bhNEroTj5NgVYKR7Qe/pQbXnOaPpvkRin3nwBL+O4QWMSlSvic7SlvAHnJJ6SUUmen3B8Ju3T7Z5Ry9fsnfjs6AaAlpahTLyUknBPkbGU2yBzATaiouxu0BptPbtWR5Xy6h5AyxouFji+glFTeURF78XLLLzD+V47nBI49h61LJHVVl23onquaLcStwPm1P0lVJHzPZpDcKowhvYoyTZzGa2MbPjHHNlbxKiCiwnVEv80CEprDplfgHoL+p/VyQzLQnqv2xLOYxz7uUTtok0JQ0GpDxJ486J6hs=
  app: acebook-gets-railed
  on:
    repo: iainaitken/acebook-team-gets-railed
  skip_cleanup: 'true'
